# Generated by Django 4.1.5 on 2023-01-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productdetail",
            name="Product_Category",
            field=models.CharField(
                choices=[("Men", "Men"), ("Womans", "Womens"), ("Kids", "Kids")],
                default=0,
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
