# Generated by Django 4.1.5 on 2023-01-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0002_productdetail_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="productdetail",
            name="Product_Stock",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
